spring:
  profiles:
    active: prod

  application:
    name: rest-with-spring-boot-and-java-erudio

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: /tmp/uploads
